// 词库数据
const wordBanks = {
    cet4: [
        { word: "abandon", phonetic: "/əˈbændən/", meaning: "v. 放弃，抛弃" },
        { word: "ability", phonetic: "/əˈbɪləti/", meaning: "n. 能力，才能" },
        { word: "absent", phonetic: "/ˈæbsənt/", meaning: "adj. 缺席的，不在的" },
        { word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "adj. 绝对的，完全的" },
        { word: "absorb", phonetic: "/əbˈsɔːb/", meaning: "v. 吸收，吸引" },
        { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的 n. 摘要" },
        { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "adj. 学术的，理论的" },
        { word: "accept", phonetic: "/əkˈsept/", meaning: "v. 接受，承认" },
        { word: "access", phonetic: "/ˈækses/", meaning: "n. 通道，入口 v. 存取" },
        { word: "accident", phonetic: "/ˈæksɪdənt/", meaning: "n. 事故，意外" },
        { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "v. 陪伴，伴奏" },
        { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "v. 完成，实现" },
        { word: "account", phonetic: "/əˈkaʊnt/", meaning: "n. 账户，账目 v. 解释" },
        { word: "accurate", phonetic: "/ˈækjərət/", meaning: "adj. 准确的，精确的" },
        { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "v. 实现，达到" },
        { word: "acquire", phonetic: "/əˈkwaɪər/", meaning: "v. 获得，取得" },
        { word: "action", phonetic: "/ˈækʃən/", meaning: "n. 行动，动作" },
        { word: "active", phonetic: "/ˈæktɪv/", meaning: "adj. 积极的，活跃的" },
        { word: "actual", phonetic: "/ˈæktʃuəl/", meaning: "adj. 实际的，真实的" },
        { word: "adapt", phonetic: "/əˈdæpt/", meaning: "v. 适应，改编" }
    ],
    cet6: [
        { word: "abbreviate", phonetic: "/əˈbriːvieɪt/", meaning: "v. 缩写，缩短" },
        { word: "abolish", phonetic: "/əˈbɒlɪʃ/", meaning: "v. 废除，取消" },
        { word: "absurd", phonetic: "/əbˈsɜːd/", meaning: "adj. 荒谬的，可笑的" },
        { word: "abundance", phonetic: "/əˈbʌndəns/", meaning: "n. 丰富，充裕" },
        { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "v. 加速，促进" },
        { word: "accessory", phonetic: "/əkˈsesəri/", meaning: "n. 附件，配件" },
        { word: "accommodate", phonetic: "/əˈkɒmədeɪt/", meaning: "v. 容纳，适应" },
        { word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/", meaning: "v. 积累，堆积" },
        { word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "adj. 足够的，适当的" },
        { word: "adjacent", phonetic: "/əˈdʒeɪsənt/", meaning: "adj. 邻近的，毗连的" },
        { word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "v. 提倡，支持 n. 支持者" },
        { word: "aesthetic", phonetic: "/iːsˈθetɪk/", meaning: "adj. 美学的，审美的" },
        { word: "affirm", phonetic: "/əˈfɜːm/", meaning: "v. 肯定，确认" },
        { word: "aggregate", phonetic: "/ˈæɡrɪɡət/", meaning: "n. 总计，集合体 adj. 总计的" },
        { word: "allocate", phonetic: "/ˈæləkeɪt/", meaning: "v. 分配，分派" },
        { word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", meaning: "adj. 模糊的，含糊的" },
        { word: "amplify", phonetic: "/ˈæmplɪfaɪ/", meaning: "v. 放大，扩大" },
        { word: "analogous", phonetic: "/əˈnæləɡəs/", meaning: "adj. 类似的，相似的" },
        { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", meaning: "v. 预期，期望" },
        { word: "apparatus", phonetic: "/ˌæpəˈreɪtəs/", meaning: "n. 设备，器械" }
    ],
    ielts: [
        { word: "sophisticated", phonetic: "/səˈfɪstɪkeɪtɪd/", meaning: "adj. 复杂的，精密的" },
        { word: "contemporary", phonetic: "/kənˈtempərəri/", meaning: "adj. 当代的，现代的" },
        { word: "substantial", phonetic: "/səbˈstænʃəl/", meaning: "adj. 大量的，重要的" },
        { word: "phenomenon", phonetic: "/fəˈnɒmɪnən/", meaning: "n. 现象，奇迹" },
        { word: "predominant", phonetic: "/prɪˈdɒmɪnənt/", meaning: "adj. 主要的，占优势的" },
        { word: "comprehensive", phonetic: "/ˌkɒmprɪˈhensɪv/", meaning: "adj. 全面的，综合的" },
        { word: "controversial", phonetic: "/ˌkɒntrəˈvɜːʃəl/", meaning: "adj. 有争议的" },
        { word: "deteriorate", phonetic: "/dɪˈtɪəriəreɪt/", meaning: "v. 恶化，变坏" },
        { word: "diversify", phonetic: "/daɪˈvɜːsɪfaɪ/", meaning: "v. 使多样化" },
        { word: "inevitable", phonetic: "/ɪnˈevɪtəbəl/", meaning: "adj. 不可避免的" },
        { word: "infrastructure", phonetic: "/ˈɪnfrəstrʌktʃər/", meaning: "n. 基础设施" },
        { word: "sustainability", phonetic: "/səˌsteɪnəˈbɪləti/", meaning: "n. 可持续性" },
        { word: "civilization", phonetic: "/ˌsɪvəlaɪˈzeɪʃən/", meaning: "n. 文明，文化" },
        { word: "preliminary", phonetic: "/prɪˈlɪmɪnəri/", meaning: "adj. 初步的，预备的" },
        { word: "revolutionary", phonetic: "/ˌrevəˈluːʃənəri/", meaning: "adj. 革命的，创新的" },
        { word: "simultaneously", phonetic: "/ˌsaɪməlˈteɪniəsli/", meaning: "adv. 同时地" },
        { word: "unprecedented", phonetic: "/ʌnˈpresɪdentɪd/", meaning: "adj. 史无前例的" },
        { word: "collaborate", phonetic: "/kəˈlæbəreɪt/", meaning: "v. 合作，协作" },
        { word: "incorporate", phonetic: "/ɪnˈkɔːpəreɪt/", meaning: "v. 包含，合并" },
        { word: "significance", phonetic: "/sɪɡˈnɪfɪkəns/", meaning: "n. 重要性，意义" }
    ],
    toefl: [
        { word: "hypothesis", phonetic: "/haɪˈpɒθəsɪs/", meaning: "n. 假设，假说" },
        { word: "methodology", phonetic: "/ˌmeθəˈdɒlədʒi/", meaning: "n. 方法论，方法学" },
        { word: "empirical", phonetic: "/ɪmˈpɪrɪkəl/", meaning: "adj. 经验的，实证的" },
        { word: "paradigm", phonetic: "/ˈpærədaɪm/", meaning: "n. 范式，模式" },
        { word: "constitute", phonetic: "/ˈkɒnstɪtuːt/", meaning: "v. 构成，组成" },
        { word: "demonstrate", phonetic: "/ˈdemənstreɪt/", meaning: "v. 证明，演示" },
        { word: "facilitate", phonetic: "/fəˈsɪlɪteɪt/", meaning: "v. 促进，使容易" },
        { word: "implement", phonetic: "/ˈɪmplɪment/", meaning: "v. 实施，执行" },
        { word: "fluctuate", phonetic: "/ˈflʌktʃueɪt/", meaning: "v. 波动，起伏" },
        { word: "manipulate", phonetic: "/məˈnɪpjuleɪt/", meaning: "v. 操纵，操作" },
        { word: "synthesize", phonetic: "/ˈsɪnθəsaɪz/", meaning: "v. 合成，综合" },
        { word: "distinguish", phonetic: "/dɪˈstɪŋɡwɪʃ/", meaning: "v. 区别，辨别" },
        { word: "proposition", phonetic: "/ˌprɒpəˈzɪʃən/", meaning: "n. 命题，建议" },
        { word: "correlation", phonetic: "/ˌkɒrəˈleɪʃən/", meaning: "n. 相关性，关联" },
        { word: "subsequent", phonetic: "/ˈsʌbsɪkwənt/", meaning: "adj. 随后的，后来的" },
        { word: "interpretation", phonetic: "/ɪnˌtɜːprɪˈteɪʃən/", meaning: "n. 解释，阐释" },
        { word: "modification", phonetic: "/ˌmɒdɪfɪˈkeɪʃən/", meaning: "n. 修改，变更" },
        { word: "configuration", phonetic: "/kənˌfɪɡəˈreɪʃən/", meaning: "n. 配置，构造" },
        { word: "supplementary", phonetic: "/ˌsʌplɪˈmentəri/", meaning: "adj. 补充的，附加的" },
        { word: "optimization", phonetic: "/ˌɒptɪmaɪˈzeɪʃən/", meaning: "n. 优化，最优化" }
    ],
    kaoyan: [
        { word: "nonetheless", phonetic: "/ˌnʌnðəˈles/", meaning: "adv. 尽管如此，然而" },
        { word: "presumably", phonetic: "/prɪˈzuːməbli/", meaning: "adv. 大概，可能" },
        { word: "whereby", phonetic: "/weəˈbaɪ/", meaning: "adv. 凭此，借以" },
        { word: "consensus", phonetic: "/kənˈsensəs/", meaning: "n. 共识，一致意见" },
        { word: "commodity", phonetic: "/kəˈmɒdəti/", meaning: "n. 商品，日用品" },
        { word: "magnitude", phonetic: "/ˈmæɡnɪtuːd/", meaning: "n. 大小，量级" },
        { word: "discourse", phonetic: "/ˈdɪskɔːs/", meaning: "n. 论述，话语" },
        { word: "subsidy", phonetic: "/ˈsʌbsədi/", meaning: "n. 补贴，津贴" },
        { word: "surplus", phonetic: "/ˈsɜːpləs/", meaning: "n. 剩余，盈余" },
        { word: "deficit", phonetic: "/ˈdefɪsɪt/", meaning: "n. 赤字，不足" },
        { word: "incentive", phonetic: "/ɪnˈsentɪv/", meaning: "n. 激励，刺激" },
        { word: "hierarchy", phonetic: "/ˈhaɪərɑːki/", meaning: "n. 等级制度，层级" },
        { word: "integrity", phonetic: "/ɪnˈteɡrəti/", meaning: "n. 正直，完整性" },
        { word: "legitimate", phonetic: "/lɪˈdʒɪtɪmət/", meaning: "adj. 合法的，正当的" },
        { word: "prosecute", phonetic: "/ˈprɒsɪkjuːt/", meaning: "v. 起诉，检举" },
        { word: "discrimination", phonetic: "/dɪˌskrɪmɪˈneɪʃən/", meaning: "n. 歧视，区别" },
        { word: "expedition", phonetic: "/ˌekspəˈdɪʃən/", meaning: "n. 远征，探险" },
        { word: "contradiction", phonetic: "/ˌkɒntrəˈdɪkʃən/", meaning: "n. 矛盾，对立" },
        { word: "jurisdiction", phonetic: "/ˌdʒʊərɪsˈdɪkʃən/", meaning: "n. 司法权，管辖权" },
        { word: "speculation", phonetic: "/ˌspekjuˈleɪʃən/", meaning: "n. 推测，投机" }
    ]
};

// 词库信息
const wordBankInfo = {
    cet4: { name: "英语四级", description: "大学英语四级核心词汇" },
    cet6: { name: "英语六级", description: "大学英语六级核心词汇" },
    ielts: { name: "雅思", description: "雅思考试核心词汇" },
    toefl: { name: "托福", description: "托福考试核心词汇" },
    kaoyan: { name: "考研词汇", description: "考研英语核心词汇" }
}; 